import { useState, type ReactNode } from 'react'
import { Activity, ArrowLeft, ArrowRight, Bike, CalendarDays, Check, ChevronRight, Cloud, Database, Eye, FileText, Flag, Home, LockKeyhole, MapPin, Plus, QrCode, Search, Send, Settings, ShieldAlert, ShieldCheck, Signal, Smartphone, Trash2, TrendingUp, UserRound, Users, Wifi, X } from 'lucide-react'
import { mockActivity, mockAdminTransactions, mockBicycles, mockPeople, mockUser, type BicycleRecord, type PersonRecord } from './mock/data'
import { db } from './lib/db'

type Screen = 'login' | 'home' | 'admin-home' | 'admin-transactions' | 'transaction-record' | 'flagged-queue' | 'bicycle-inventory' | 'ownership-chain' | 'registry-profile' | 'agent-management' | 'agent-onboarding' | 'agent-terminal' | 'reports-exports' | 'transaction' | 'register' | 'search' | 'details' | 'activity' | 'profile'
type Role = 'AGENT' | 'ADMIN'

const navItems: { screen: Screen; label: string; icon: typeof Home }[] = [
  { screen: 'home', label: 'Home', icon: Home },
  { screen: 'search', label: 'Search', icon: Search },
  { screen: 'activity', label: 'Activity', icon: Activity },
  { screen: 'profile', label: 'Profile', icon: UserRound },
]

export default function App() {
  const [screen, setScreen] = useState<Screen>('login')
  const [role, setRole] = useState<Role>('AGENT')
  const [selected, setSelected] = useState<BicycleRecord>(mockBicycles[0])
  const [query, setQuery] = useState('')
  const [transactionStep, setTransactionStep] = useState(0)
  const [saved, setSaved] = useState(false)
  const [warning, setWarning] = useState(false)
  const [ownerDetails, setOwnerDetails] = useState<PersonRecord | null>(null)

  const openDetails = (record: BicycleRecord) => { setSelected(record); setScreen('details') }
  const go = (next: Screen) => { setSaved(false); if (next === 'transaction') setTransactionStep(0); setScreen(next) }

  if (screen === 'login') return <Login onLogin={() => go('home')} />

  return <div className="terminal-shell">
    <header className="terminal-header">
      {screen !== 'home' && <button className="back-button" onClick={() => go(screen === 'details' ? 'search' : 'home')} aria-label="Go back"><ArrowLeft size={17} /></button>}
      <strong>{screenTitle(screen)}</strong>
      <span className="wifi-badge" title="Online"><Wifi size={14} /></span>
    </header>
    <div className="terminal-content">
      {screen === 'home' && <HomeScreen onNavigate={go} onSelect={openDetails} />}
      {screen === 'admin-home' && <AdminHomeScreen onNavigate={go} />}
      {screen === 'admin-transactions' && <AdminTransactionsScreen onNavigate={go} />}
      {screen === 'transaction-record' && <AdminRecordScreen onNavigate={go} />}
      {screen === 'flagged-queue' && <FlaggedQueueScreen onNavigate={go} />}
      {screen === 'bicycle-inventory' && <BicycleInventoryScreen onNavigate={go} />}
      {screen === 'ownership-chain' && <OwnershipChainScreen onNavigate={go} />}
      {screen === 'registry-profile' && <RegistryProfileScreen onNavigate={go} />}
      {screen === 'agent-management' && <AgentManagementScreen onNavigate={go} />}
      {screen === 'agent-onboarding' && <AgentOnboardingScreen onNavigate={go} />}
      {screen === 'agent-terminal' && <AgentTerminalScreen onNavigate={go} />}
      {screen === 'reports-exports' && <ReportsExportsScreen onNavigate={go} />}
      {screen === 'transaction' && <TransactionFlow step={transactionStep} setStep={setTransactionStep} saved={saved} onSave={() => setSaved(true)} onCancel={() => go('home')} onViewOwner={setOwnerDetails} />}
      {screen === 'register' && <RegisterScreen onSave={() => setSaved(true)} saved={saved} onCancel={() => go('home')} onViewOwner={setOwnerDetails} />}
      {screen === 'search' && <SearchScreen query={query} setQuery={setQuery} onSelect={openDetails} />}
      {screen === 'details' && <DetailsScreen record={selected} />}
      {screen === 'activity' && <ActivityScreen />}
      {screen === 'profile' && <ProfileScreen onWarning={() => setWarning(true)} onLogout={() => { setRole('AGENT'); go('login') }} onAdmin={() => { setRole('ADMIN'); go('admin-home') }} />}
    </div>
    {role === 'ADMIN' ? <AdminBottomNav screen={screen} onNavigate={go} /> : screen !== 'transaction' && screen !== 'register' && screen !== 'details' && <BottomNav screen={screen} onNavigate={go} />}
    {warning && <WarningModal onClose={() => setWarning(false)} />}
    {ownerDetails && <OwnerDetailsModal person={ownerDetails} onClose={() => setOwnerDetails(null)} />}
  </div>
}

function screenTitle(screen: Screen) {
  return { home: 'Agent Dashboard', 'admin-home': 'Biketrack Admin', 'admin-transactions': 'All Transactions', 'transaction-record': 'Transaction Record', 'flagged-queue': 'Flagged Queue', 'bicycle-inventory': 'Bicycle Inventory', 'ownership-chain': 'Ownership Chain', 'registry-profile': 'Registry Profile', 'agent-management': 'Field Agent Management', 'agent-onboarding': 'Agent Onboarding', 'agent-terminal': 'Agent Terminal', 'reports-exports': 'Reports & Exports', transaction: 'New Transaction', register: 'Register Bicycle', search: 'Search Field Records', details: 'Transaction Details', activity: 'Recent Activity', profile: 'Agent Profile & Settings', login: 'Login' }[screen]
}

function Login({ onLogin }: { onLogin: () => void }) {
  return <main className="login-screen">
    <div className="login-hero"><div className="hero-bike"><Bike size={22} /></div><strong>CycleTrack</strong><small>FIELD AGENT TERMINAL</small></div>
    <section className="login-panel"><p className="screen-kicker">SECURE ENTRY</p><p className="login-copy">Authorized personnel only. PIN required for field access.</p>
      <label><span><Smartphone size={12} /> Agent phone</span><input placeholder="000-000-0000" /></label>
      <label><span><LockKeyhole size={12} /> Security PIN</span><div className="password-input"><input type="password" placeholder="••••" /><Eye size={15} /></div></label>
      <button className="action-button" onClick={onLogin}>Initialize terminal <ArrowRight size={16} /></button>
      <button className="quiet-button">Forgot credentials?</button>
    </section>
    <footer className="offline-bar"><span><Signal size={14} /> Connectivity</span><strong>Offline-ready mode</strong><small>v2.4.1-field</small></footer>
  </main>
}

function HomeScreen({ onNavigate, onSelect }: { onNavigate: (screen: Screen) => void; onSelect: (record: BicycleRecord) => void }) {
  return <>
    <section className="welcome"><p className="screen-kicker">LOGGED IN AS FIELD AGENT</p><h1>Operations Center</h1></section>
    <button className="feature-button" onClick={() => onNavigate('transaction')}><span className="feature-icon"><FileText size={22} /></span><span><strong>New Transaction</strong><small>Initiate bicycle sale or transfer</small></span><ArrowRight /></button>
    <button className="feature-button" onClick={() => onNavigate('register')}><span className="feature-icon"><Bike size={22} /></span><span><strong>Register Bicycle</strong><small>Capture serial & owner data</small></span><ArrowRight /></button>
    <div className="quick-grid"><button onClick={() => onNavigate('search')}><Search size={20} /><strong>Search</strong></button><button onClick={() => onNavigate('activity')}><Activity size={20} /><strong>Activity</strong></button></div>
    <p className="section-label">Session intelligence</p><div className="intelligence"><div><small>Today's tasks</small><strong>12<span>/15</span></strong></div><div><small>Local cache</small><strong className="lime">42MB</strong></div><footer><Database size={13} /> Offline database v2.4.1 active</footer></div>
    <p className="section-label">Last modified record</p><button className="record-row" onClick={() => onSelect(mockBicycles[0])}><span className="record-icon"><Bike size={18} /></span><span><strong>TXN-88290-B</strong><small>◷ Modified 14 mins ago</small></span><ChevronRight size={17} /></button>
  </>
}

function AdminHomeScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) {
  const metrics = [['Total registered', '14,282', '+12.5%', TrendingUp], ['Active agents', '184', '↑ 4', Users], ['Pending sync', '42', '-8%', Cloud], ['Flagged alerts', '09', '+2', Flag]] as const
  const flags = [['Specialized Sirrus X 4.0', 'Stolen report match #SR-928', '14h ago'], ['Cannondale Topstone 1', 'Duplicate serial entry', '11h ago'], ['Trek Marlin 7 Gen 2', 'Invalid ownership transfer', '3h ago']]
  const modules = [['Transactions', 'Historical log', Activity], ['Bicycles', 'Registry inventory', Bike], ['People', 'Owner directory', Users], ['Field agents', 'Team management', UserRound], ['Reports', 'Export & analytics', FileText], ['Flagged', 'Priority queue', Flag]] as const
  return <section className="admin-home">
    <div className="admin-brand"><span>BIKETRACK ADMIN</span><small>RECORD-KEEPING CONTROL CENTER</small></div>
    <div className="admin-metrics">{metrics.map(([label, value, trend, Icon]) => <div className="admin-metric" key={label}><div><Icon size={14} /><b>{trend}</b></div><small>{label}</small><strong>{value}</strong></div>)}</div>
    <div className="admin-section-heading"><span><Flag size={13} /> Flagged queue</span><button onClick={() => onNavigate('search')}>View all</button></div><p className="admin-subtitle">Immediate resolution required</p>
    <div className="flag-list">{flags.map(([name, reason, time]) => <button key={name} className="flag-item" onClick={() => onNavigate('search')}><span><Flag size={13} /></span><strong>{name}<small>{reason}</small></strong><em>{time}</em></button>)}</div>
    <p className="admin-section-label"><TrendingUp size={11} /> Control modules</p><div className="module-grid">{modules.map(([label, copy, Icon], index) => <button key={label} className={index === 5 ? 'module danger' : 'module'} onClick={() => onNavigate(['admin-transactions', 'bicycle-inventory', 'registry-profile', 'agent-management', 'reports-exports', 'flagged-queue'][index] as Screen)}><Icon size={15} /><strong>{label}</strong><small>{copy}</small>{index === 5 && <b>!</b>}</button>)}</div>
    <button className="admin-register" onClick={() => onNavigate('register')}><Plus size={14} /> Register new bicycle</button>
    <div className="admin-footer-actions"><button onClick={() => onNavigate('profile')}>Manage profile</button><button onClick={() => onNavigate('profile')}>System settings</button></div><p className="admin-integrity">"Integrity in every record, security in every chain."<br /><span>Last sync: 5:38:30 PM (UTC-5)</span></p>
  </section>
}

function AdminTransactionsScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) {
  const [query, setQuery] = useState('')
  const transactions = mockAdminTransactions.filter((transaction) => `${transaction.id} ${transaction.bicycle} ${transaction.frameNumber} ${transaction.parties} ${transaction.agent}`.toLowerCase().includes(query.toLowerCase()))
  return <section className="admin-transactions"><div className="admin-page-heading"><div><p className="screen-kicker">CONTROL MODULE</p><h1>All Transactions</h1><p>Network-wide historical record</p></div><button className="admin-icon-button" aria-label="Export transactions"><Send size={15} /></button></div><div className="admin-transaction-stats"><span><small>Total records</small><strong>3,672</strong></span><span><small>This month</small><strong>184</strong></span><span><small>Flagged</small><strong className="rust-number">09</strong></span></div><div className="admin-search"><Search size={14} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search ID, frame, owner..." /></div><div className="admin-filters"><button className="selected">All</button><button>Sales</button><button>Transfers</button><button>Flagged</button></div><p className="admin-result-count">Showing {transactions.length} of 3,672 transactions</p><div className="transaction-list">{transactions.map((transaction) => <button className="transaction-item" key={transaction.id} onClick={() => onNavigate('transaction-record')}><div className="transaction-item-head"><span className={`transaction-type ${transaction.type.toLowerCase()}`}>{transaction.type}</span><em className={transaction.status === 'Verified' ? 'verified' : transaction.status === 'Flagged' ? 'flagged' : 'pending'}>{transaction.status}</em></div><strong>{transaction.bicycle}</strong><small className="transaction-frame">{transaction.frameNumber} · {transaction.id}</small><div className="transaction-meta"><span>{transaction.parties}</span><span>{transaction.agent}</span><span>{transaction.date}</span></div><ChevronRight size={15} /></button>)}</div>{transactions.length === 0 && <p className="empty-state">No transactions match this search.</p>}<button className="secondary-button admin-load">Load more records</button></section>
}

function AdminRecordScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) { return <AdminPanel title="Transaction Record" kicker="REFERENCE ID · TX-98422-BK"><div className="admin-record-alert"><ShieldAlert size={14} /><strong>Resolution required</strong><small>Flagged record requires administrator review.</small></div><AdminInfo title="Transaction summary" rows={['SALE · Nov 24, 2023 · 14:22 UTC', 'Specialized Sirrus X 4.0 · M2S-928', 'Marcus Thorne → Sarah Jenkins', 'Processed by AGENT_8821']} /><button className="admin-wide-button" onClick={() => onNavigate('flagged-queue')}>Open flagged queue</button></AdminPanel> }
function FlaggedQueueScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) { return <AdminPanel title="Flagged Queue" kicker="ACTIVE INCIDENTS · 3"><div className="queue-metrics"><b>12<small>Urgent</small></b><b>08<small>Pending</small></b><b>45<small>Resolved</small></b></div>{['Specialized Rockhopper Expert', 'Cannondale Synapse Carbon', 'Trek Domane AL 2'].map((name) => <button className="incident-card" key={name} onClick={() => onNavigate('transaction-record')}><Flag size={14} /><strong>{name}<small>Serial mismatch and ownership validation required</small></strong><em>Review</em></button>)}</AdminPanel> }
function BicycleInventoryScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) { return <AdminPanel title="Bicycle Inventory" kicker="REGISTRY INVENTORY"><div className="admin-search"><Search size={14} /><input placeholder="Search SN, Brand, or Owner..." /></div><div className="inventory-summary"><strong>1,284<small>Total records</small></strong><strong className="rust-number">42<small>Flagged units</small></strong></div>{mockBicycles.concat(mockBicycles).map((bike, index) => <button className="inventory-item" key={`${bike.id}-${index}`} onClick={() => onNavigate('ownership-chain')}><Bike size={18} /><strong>{bike.name}<small>SN: {bike.frameNumber} · {bike.owner}</small></strong><em>{index % 3 === 1 ? 'Flagged' : 'Registered'}</em><ChevronRight size={14} /></button>)}</AdminPanel> }
function OwnershipChainScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) { return <AdminPanel title="Ownership Chain" kicker="SPECIALIZED ROCKHOPPER ELITE"><div className="chain-card"><small>Current owner</small><strong>Marcus Vane</strong><span>Field Protocol 04</span></div>{['Registration · Feb 14, 2024', 'Transfer · Jan 20, 2024', 'Resolution · Nov 15, 2023'].map((event) => <div className="chain-event" key={event}><span></span><strong>{event}<small>Verified record with audit metadata and location.</small></strong></div>)}<button className="admin-wide-button" onClick={() => onNavigate('transaction-record')}>Full export</button></AdminPanel> }
function RegistryProfileScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) { return <AdminPanel title="Registry Profile" kicker="MARCUS V. STERLING"><div className="registry-identity"><span className="profile-avatar">MV</span><strong>Verified registry owner<small>REG-99285-MV · Sector 4 Administrative District</small></strong></div><div className="inventory-summary"><strong>2<small>Currently owned</small></strong><strong className="rust-number">1<small>System flags</small></strong></div><button className="inventory-item" onClick={() => onNavigate('bicycle-inventory')}><Bike size={18} /><strong>Specialized Rockhopper Expert<small>SP-88218-Z2 · Active residence</small></strong><em>Registered</em></button><button className="inventory-item"><Bike size={18} /><strong>Cannondale Quick Disc 3<small>CN-11923-Q · Active residence</small></strong><em>Registered</em></button></AdminPanel> }
function AgentManagementScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) { const [agents, setAgents] = useState(['Marcus Thorne', 'Sarah Jenkins', 'David Vance', 'Elena Rodriguez']); const [pendingDelete, setPendingDelete] = useState<string | null>(null); const deleteAgent = (name: string) => { setAgents((current) => current.filter((agent) => agent !== name)); setPendingDelete(null) }; return <AdminPanel title="Field Agent Management" kicker="AUTHORIZED PERSONNEL"><div className="admin-search"><Search size={14} /><input placeholder="Search by name or ID..." /></div><div className="inventory-summary"><strong>{agents.length}<small>Total</small></strong><strong>18<small>Active</small></strong><strong>06<small>Deploy</small></strong></div>{agents.map((name) => <div className="agent-item" key={name}><button className="agent-main" onClick={() => onNavigate('agent-terminal')}><span className="profile-avatar">{name.split(' ').map((part) => part[0]).join('')}</span><strong>{name}<small>ONLINE · Field Agent · 142 records</small></strong><ChevronRight size={14} /></button><button className="delete-agent" onClick={() => setPendingDelete(name)} aria-label={`Delete ${name}`} title="Delete agent"><Trash2 size={14} /></button></div>)}<button className="admin-wide-button" onClick={() => onNavigate('agent-onboarding')}><Plus size={14} /> Onboard new agent</button>{pendingDelete && <div className="delete-confirm"><p>Delete <strong>{pendingDelete}</strong>?</p><small>This removes the agent from the local admin preview. Existing records remain auditable.</small><div><button onClick={() => setPendingDelete(null)}>Cancel</button><button className="danger-confirm" onClick={() => deleteAgent(pendingDelete)}>Delete agent</button></div></div>}</AdminPanel> }
function AgentOnboardingScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) { const [phone, setPhone] = useState(''); const [pin, setPin] = useState(''); return <AdminPanel title="Agent Onboarding" kicker="STEP 1 OF 2"><label>Full legal name<input placeholder="e.g. Marcus Thorne" /></label><label>Assigned tactical ID<input placeholder="BT-AGENT-772" /></label><div className="two-fields"><label>Operational role<select><option>Field Agent</option><option>Supervisor</option></select></label><label>Clearance level<select><option>Level 01</option><option>Level 02</option></select></label></div><label>Official phone number<input value={phone} onChange={(event) => setPhone(event.target.value)} type="tel" placeholder="+233 24 000 0000" /></label><label>Security PIN<input value={pin} onChange={(event) => setPin(event.target.value)} type="password" inputMode="numeric" maxLength={6} placeholder="Create 4-6 digit PIN" /></label><label>Official email address<input placeholder="agent.name@biketrack.gov" /></label><button className="admin-wide-button" disabled={!phone || pin.length < 4} onClick={() => onNavigate('agent-management')}>Create agent credentials <ArrowRight size={14} /></button></AdminPanel> }
function AgentTerminalScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) { return <AdminPanel title="Agent Terminal" kicker="MARCUS THORNE · LEVEL 3 AGENT"><div className="inventory-summary"><strong>12<small>Logins today</small></strong><strong>98.4%<small>Success rate</small></strong></div><p className="admin-section-label">Access protocols</p>{['New registration', 'Asset transfers', 'Flag authority', 'Remote override'].map((name, index) => <div className="protocol-row" key={name}><ShieldCheck size={14} /><strong>{name}<small>{index < 2 ? 'Allow agent to record and sync records' : 'Grant power to review suspicious assets'}</small></strong><span className={index < 2 ? 'toggle on' : 'toggle'} /></div>)}<button className="admin-wide-button" onClick={() => onNavigate('agent-management')}>Return to agents</button></AdminPanel> }
function ReportsExportsScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) { return <AdminPanel title="Reports & Exports" kicker="ADVANCED ANALYTICS"><div className="report-hero"><TrendingUp size={25} /><strong>Generate encrypted audit reports</strong><small>Industry-standard audit trails and operational summaries.</small></div>{['Transaction audit log', 'Agent performance', 'Flagged incident summary', 'Inventory status'].map((name) => <button className="report-option" key={name}><FileText size={15} /><strong>{name}<small>Full history of registry actions and transactions</small></strong><ChevronRight size={14} /></button>)}<button className="admin-wide-button" onClick={() => onNavigate('admin-home')}>Preview report data</button></AdminPanel> }
function AdminPanel({ title, kicker, children }: { title: string; kicker: string; children: ReactNode }) { return <section className="admin-panel"><p className="screen-kicker">{kicker}</p><h1>{title}</h1>{children}</section> }
function AdminInfo({ title, rows }: { title: string; rows: string[] }) { return <div className="admin-info"><h2>{title}</h2>{rows.map((row) => <p key={row}>{row}</p>)}</div> }

type TransactionDraft = { type: 'SALE' | 'TRANSFER'; frameNumber: string; bicycleBrand: string; bicycleModel: string; bicycleColor: string; distinguishingFeatures: string; sellerName: string; sellerNationalId: string; sellerPhone: string; sellerCell: string; sellerSector: string; sellerVillage: string; buyerName: string; buyerNationalId: string; buyerPhone: string; buyerCell: string; buyerSector: string; buyerVillage: string; bicyclePrice: string; serviceFee: string; reason: string }

const emptyTransaction: TransactionDraft = { type: 'SALE', frameNumber: '', bicycleBrand: '', bicycleModel: '', bicycleColor: '', distinguishingFeatures: '', sellerName: '', sellerNationalId: '', sellerPhone: '', sellerCell: '', sellerSector: '', sellerVillage: '', buyerName: '', buyerNationalId: '', buyerPhone: '', buyerCell: '', buyerSector: '', buyerVillage: '', bicyclePrice: '', serviceFee: '5.00', reason: '' }

function TransactionFlow({ step, setStep, saved, onSave, onCancel, onViewOwner }: { step: number; setStep: (step: number) => void; saved: boolean; onSave: () => void; onCancel: () => void; onViewOwner: (person: PersonRecord) => void }) {
  const [draft, setDraft] = useState<TransactionDraft>(emptyTransaction)
  const [serialChecked, setSerialChecked] = useState(false)
  const [serialFound, setSerialFound] = useState(false)
  const [serialOwner, setSerialOwner] = useState<PersonRecord | null>(null)
  const [serialConfirmed, setSerialConfirmed] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const update = <K extends keyof TransactionDraft>(key: K, value: TransactionDraft[K]) => setDraft((current) => ({ ...current, [key]: value }))
  const verifySerial = async () => { const normalized = draft.frameNumber.trim().toLowerCase(); const bicycle = mockBicycles.find((item) => item.frameNumber.toLowerCase() === normalized); const cachedBicycle = (await db.cachedBicycles.toArray()).find((record) => ((record.data as { frameNumber?: string }).frameNumber ?? '').toLowerCase() === normalized); const cachedOwnerId = cachedBicycle ? (cachedBicycle.data as { currentOwnerId?: string }).currentOwnerId : undefined; const cachedOwner = cachedOwnerId ? (await db.cachedPeople.get(cachedOwnerId))?.data as PersonRecord | undefined : undefined; setSerialOwner(bicycle ? mockPeople.find((person) => person.name === bicycle.owner) ?? null : cachedOwner ?? null); setSerialFound(Boolean(bicycle || cachedBicycle)); setSerialConfirmed(false); setSerialChecked(true) }
  const total = (Number(draft.bicyclePrice) || 0) + (Number(draft.serviceFee) || 0)
  const saveTransaction = async () => { setIsSaving(true); const bicycleId = `bicycle-${draft.frameNumber.trim().toLowerCase()}`; const cachedPeople = await db.cachedPeople.toArray(); const parties = [{ name: draft.sellerName, nationalId: draft.sellerNationalId, phone: draft.sellerPhone, cell: draft.sellerCell, sector: draft.sellerSector, village: draft.sellerVillage }, { name: draft.buyerName, nationalId: draft.buyerNationalId, phone: draft.buyerPhone, cell: draft.buyerCell, sector: draft.buyerSector, village: draft.buyerVillage }]; const personRefs = parties.map((party) => { const existing = mockPeople.find((person) => person.nationalId.toLowerCase() === party.nationalId.trim().toLowerCase()) ?? cachedPeople.find((record) => (record.data as PersonRecord).nationalId?.toLowerCase() === party.nationalId.trim().toLowerCase()); return existing?.id ?? `person-${party.nationalId.trim()}` }); for (const [index, party] of parties.entries()) { const alreadyStored = mockPeople.some((person) => person.nationalId.toLowerCase() === party.nationalId.trim().toLowerCase()) || cachedPeople.some((record) => (record.data as PersonRecord).nationalId?.toLowerCase() === party.nationalId.trim().toLowerCase()); if (!alreadyStored && party.nationalId.trim()) await db.cachedPeople.put({ id: personRefs[index], data: { id: personRefs[index], ...party }, updatedAt: Date.now() }) } await db.cachedBicycles.put({ id: bicycleId, data: { frameNumber: draft.frameNumber, brand: draft.bicycleBrand, model: draft.bicycleModel, color: draft.bicycleColor, distinguishingFeatures: draft.distinguishingFeatures }, updatedAt: Date.now() }); await db.pendingTransactions.put({ id: crypto.randomUUID(), payload: { ...draft, total, bicycleId, sellerPersonId: personRefs[0], buyerPersonId: personRefs[1], queuedAt: new Date().toISOString() }, createdAt: Date.now() }); setIsSaving(false); onSave() }
  if (saved) return <Success title="Transaction queued" copy="The bicycle and transaction are saved locally. They will sync when connectivity returns." onDone={onCancel} />
  const steps = ['Type', 'Serial', 'Bicycle', 'Parties', 'Review', 'Done']
  const next = () => { if (step === 0) setStep(1); else if (step === 1 && serialChecked && (!serialFound || serialConfirmed)) setStep(serialFound ? 3 : 2); else if (step === 2) setStep(3); else if (step === 3) setStep(4); else if (step === 4) void saveTransaction() }
  return <section className="flow-screen"><div className="stepper">{steps.map((label, index) => <span key={label} className={index <= step ? 'current' : ''}><i>{index + 1}</i><small>{label}</small></span>)}</div>
    {step === 0 && <ChoiceStep type={draft.type} onTypeChange={(type) => update('type', type)} />}
    {step === 1 && <SerialStep value={draft.frameNumber} onChange={(value) => update('frameNumber', value)} checked={serialChecked} found={serialFound} owner={serialOwner} confirmed={serialConfirmed} onVerify={verifySerial} onConfirm={() => setSerialConfirmed(true)} onViewOwner={onViewOwner} />}
    {step === 2 && <BicycleCaptureStep draft={draft} update={update} />}
    {step === 3 && <PartyStep draft={draft} update={update} />}
    {step === 4 && <ReviewStep draft={draft} total={total} onPrint={() => window.print()} />}
    <div className="flow-actions"><button className="quiet-button" onClick={step === 0 ? onCancel : () => setStep(step === 3 && serialFound ? 1 : step - 1)}>Back</button><button className="action-button" disabled={(step === 1 && !serialChecked) || isSaving} onClick={next}>{isSaving ? 'Saving...' : step === 4 ? 'Save transaction' : 'Continue'} <ArrowRight size={15} /></button></div>
  </section>
}

function ChoiceStep({ type, onTypeChange }: { type: TransactionDraft['type']; onTypeChange: (type: TransactionDraft['type']) => void }) { const options: [TransactionDraft['type'], string, string, typeof FileText][] = [['SALE', 'Sell', 'Record a sale and permanent change of ownership', FileText], ['TRANSFER', 'Ownership transfer', 'Transfer ownership without a sale price', MapPin]]; return <div className="flow-body"><h2>Select transaction type</h2><p>Choose the record type for this field operation. Both flows verify the people involved by national ID.</p>{options.map(([value, title, copy, Icon]) => <button className={`choice-card ${type === value ? 'selected-choice' : ''}`} key={value} onClick={() => onTypeChange(value)}><span><Icon size={19} /></span><b>{title}</b><small>{copy}</small><ChevronRight /></button>)}</div> }
function SerialStep({ value, onChange, checked, found, owner, confirmed, onVerify, onConfirm, onViewOwner }: { value: string; onChange: (value: string) => void; checked: boolean; found: boolean; owner: PersonRecord | null; confirmed: boolean; onVerify: () => void; onConfirm: () => void; onViewOwner: (person: PersonRecord) => void }) { return <div className="flow-body"><h2>Verify serial number</h2><p>Check the local database before creating a bicycle record.</p><label>Frame serial number<div className="serial-input"><QrCode size={16} /><input value={value} onChange={(event) => onChange(event.target.value)} placeholder="E.G. AB12345678" /><Smartphone size={16} /></div></label><button className="secondary-button" onClick={() => void onVerify()}><Search size={15} /> Verify database</button>{checked && found && <div className="duplicate-warning"><ShieldAlert size={17} /><span><strong>Duplicate bicycle found</strong><small>This serial is already linked to an owner. Resolve the issue before continuing.</small>{owner && <><button className="owner-details-link" onClick={() => onViewOwner(owner)}>View owner details <ArrowRight size={12} /></button><div className="owner-details"><b>{owner.name}</b><small>{owner.nationalId} · {owner.phone}</small><small>{owner.sector} · {owner.village}</small></div></>}</span>{confirmed ? <Check className="confirmation-check" size={17} /> : <button className="confirm-warning" onClick={onConfirm}>Issue resolved</button>}</div>}{checked && !found && <div className="verification-result not-found"><Check size={15} /><span><strong>Serial available</strong><small>No bicycle record was found. Continue to capture the bicycle.</small></span></div>}<p className="section-label">Common serial locations</p><div className="location-grid"><span>Bottom bracket<b>Under pedals</b></span><span>Head tube<b>Front of frame</b></span><span>Seat tube<b>Near saddle</b></span><span>Rear dropout<b>Back wheel hub</b></span></div></div> }
function BicycleCaptureStep({ draft, update }: { draft: TransactionDraft; update: <K extends keyof TransactionDraft>(key: K, value: TransactionDraft[K]) => void }) { return <div className="flow-body"><h2>Record the bicycle</h2><p>This frame is new to the database. Capture its identifying details before recording the parties.</p><div className="capture-summary"><span>Frame serial<strong>{draft.frameNumber || 'Not entered'}</strong></span><span className="not-found-label">New bicycle record</span></div><div className="two-fields"><label>Brand<input value={draft.bicycleBrand} onChange={(event) => update('bicycleBrand', event.target.value)} placeholder="e.g. Trek" /></label><label>Model<input value={draft.bicycleModel} onChange={(event) => update('bicycleModel', event.target.value)} placeholder="e.g. Marlin 7" /></label></div><div className="two-fields"><label>Color<input value={draft.bicycleColor} onChange={(event) => update('bicycleColor', event.target.value)} placeholder="e.g. black" /></label><label>Photo reference<input placeholder="Optional photo ID" /></label></div><label>Distinguishing features<textarea value={draft.distinguishingFeatures} onChange={(event) => update('distinguishingFeatures', event.target.value)} placeholder="Scratches, markings, accessories" /></label></div> }
function PartyStep({ draft, update }: { draft: TransactionDraft; update: <K extends keyof TransactionDraft>(key: K, value: TransactionDraft[K]) => void }) { return <div className="flow-body"><h2>Record both parties</h2><p>National ID is the primary identifier. Capture contact and local area details for each participant.</p><PartyFields label="Seller (outbound)" prefix="seller" draft={draft} update={update} /><PartyFields label="Buyer (inbound)" prefix="buyer" draft={draft} update={update} /><label>Reason for transfer or mismatch<textarea value={draft.reason} onChange={(event) => update('reason', event.target.value)} placeholder="Required when seller differs from current owner" /></label><div className="price-fields"><label>Bicycle price<input type="number" min="0" value={draft.bicyclePrice} onChange={(event) => update('bicyclePrice', event.target.value)} placeholder="0.00" /></label><label>Service fee<input type="number" min="0" value={draft.serviceFee} onChange={(event) => update('serviceFee', event.target.value)} /></label></div></div> }
function PartyFields({ label, prefix, draft, update }: { label: string; prefix: 'seller' | 'buyer'; draft: TransactionDraft; update: <K extends keyof TransactionDraft>(key: K, value: TransactionDraft[K]) => void }) {
  const [lookupState, setLookupState] = useState<'idle' | 'checking' | 'found' | 'missing'>('idle')
  const lookup = async () => {
    const nationalId = draft[`${prefix}NationalId`].trim().toLowerCase()
    if (!nationalId) return
    setLookupState('checking')
    const mockPerson = mockPeople.find((person) => person.nationalId.toLowerCase() === nationalId)
    const cachedPerson = mockPerson ? undefined : (await db.cachedPeople.toArray()).map((record) => record.data as PersonRecord).find((person) => person.nationalId?.toLowerCase() === nationalId)
    const person = mockPerson ?? cachedPerson
    if (!person) { setLookupState('missing'); return }
    update(`${prefix}Name`, person.name)
    update(`${prefix}NationalId`, person.nationalId)
    update(`${prefix}Phone`, person.phone)
    update(`${prefix}Cell`, person.cell)
    update(`${prefix}Sector`, person.sector)
    update(`${prefix}Village`, person.village)
    setLookupState('found')
  }
  const status = lookupState === 'found' ? <div className="person-link-status found"><Check size={13} /> Existing person linked from database</div> : lookupState === 'missing' ? <div className="person-link-status missing"><UserRound size={13} /> Person not found. Complete the fields to create a new person.</div> : null
  return <fieldset className="party-fieldset"><legend>{label}</legend><div className="person-id-lookup"><label>National ID (primary key)<input value={draft[`${prefix}NationalId`]} onChange={(event) => { update(`${prefix}NationalId`, event.target.value); setLookupState('idle') }} placeholder="Enter national ID first" /></label><button className="secondary-button" disabled={lookupState === 'checking'} onClick={() => void lookup()}>{lookupState === 'checking' ? 'Checking...' : 'Look up person'}</button></div>{status}<label>Name<input value={draft[`${prefix}Name`]} readOnly={lookupState === 'found'} onChange={(event) => update(`${prefix}Name`, event.target.value)} placeholder="Full legal name" /></label><div className="two-fields"><label>Phone<input value={draft[`${prefix}Phone`]} readOnly={lookupState === 'found'} onChange={(event) => update(`${prefix}Phone`, event.target.value)} placeholder="Primary phone" /></label><label>Cell<input value={draft[`${prefix}Cell`]} readOnly={lookupState === 'found'} onChange={(event) => update(`${prefix}Cell`, event.target.value)} placeholder="Cell number" /></label></div><div className="two-fields"><label>Sector<input value={draft[`${prefix}Sector`]} readOnly={lookupState === 'found'} onChange={(event) => update(`${prefix}Sector`, event.target.value)} placeholder="Sector" /></label><label>Village<input value={draft[`${prefix}Village`]} readOnly={lookupState === 'found'} onChange={(event) => update(`${prefix}Village`, event.target.value)} placeholder="Village" /></label></div></fieldset>
}
function ReviewStep({ draft, total, onPrint }: { draft: TransactionDraft; total: number; onPrint: () => void }) { return <div className="flow-body"><h2>Review transaction</h2><p>Check the record before saving. The PDF is formatted for printing and contains the transaction summary.</p><div className="review-summary"><span>Transaction type<strong>{draft.type === 'SALE' ? 'Ownership transfer / sale' : 'Ownership transfer'}</strong></span><span>Bicycle<strong>{draft.bicycleBrand || 'New'} {draft.bicycleModel || 'record'} · {draft.frameNumber || 'No serial'}</strong></span><span>Seller and buyer<strong>{draft.sellerName || 'Seller pending'} → {draft.buyerName || 'Buyer pending'}</strong></span><span>Amounts<strong>Bicycle {draft.bicyclePrice || '0.00'} + service {draft.serviceFee || '0.00'} = {total.toFixed(2)}</strong></span></div><button className="secondary-button print-button" onClick={onPrint}><FileText size={15} /> Preview / print transaction PDF</button><div className="audit-note"><ShieldCheck size={15} /> This action will be added to the audit log.</div></div> }

type RegistrationDraft = { frameNumber: string; brand: string; model: string; color: string; features: string; person: PersonRecord | null }
type RegistrationPhase = 'serial' | 'bicycle' | 'person-search' | 'person-new' | 'review'

function RegisterScreen({ saved, onSave, onCancel, onViewOwner }: { saved: boolean; onSave: () => void; onCancel: () => void; onViewOwner: (person: PersonRecord) => void }) {
  const [phase, setPhase] = useState<RegistrationPhase>('serial')
  const [draft, setDraft] = useState<RegistrationDraft>({ frameNumber: '', brand: '', model: '', color: '', features: '', person: null })
  const [serialOwner, setSerialOwner] = useState<PersonRecord | null>(null)
  const [serialConfirmed, setSerialConfirmed] = useState(false)
  const [serialChecked, setSerialChecked] = useState(false)
  const [personQuery, setPersonQuery] = useState('')
  const [personChecked, setPersonChecked] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const [newPerson, setNewPerson] = useState({ name: '', nationalId: '', phone: '', cell: '', sector: '', village: '' })
  const updateBicycle = (key: keyof Omit<RegistrationDraft, 'person'>, value: string) => setDraft((current) => ({ ...current, [key]: value }))
  const updatePerson = (key: keyof typeof newPerson, value: string) => setNewPerson((current) => ({ ...current, [key]: value }))
  const verifySerial = async () => { const normalized = draft.frameNumber.trim().toLowerCase(); const bicycle = mockBicycles.find((item) => item.frameNumber.toLowerCase() === normalized); const cachedBicycle = (await db.cachedBicycles.toArray()).find((record) => ((record.data as { frameNumber?: string }).frameNumber ?? '').toLowerCase() === normalized); const cachedOwnerId = cachedBicycle ? (cachedBicycle.data as { currentOwnerId?: string }).currentOwnerId : undefined; const cachedOwner = cachedOwnerId ? (await db.cachedPeople.get(cachedOwnerId))?.data as PersonRecord | undefined : undefined; const owner = bicycle ? mockPeople.find((person) => person.name === bicycle.owner) ?? null : cachedOwner ?? null; setSerialOwner(owner); setSerialConfirmed(false); setSerialChecked(true) }
  const findPerson = () => { setPersonChecked(true); const person = mockPeople.find((item) => `${item.name} ${item.nationalId}`.toLowerCase().includes(personQuery.toLowerCase().trim())); if (person) setDraft((current) => ({ ...current, person })) }
  const saveRegistration = async () => { if (!draft.person) return; setIsSaving(true); const personId = draft.person.id || `person-${draft.person.nationalId}`; const bicycleId = `bicycle-${draft.frameNumber.trim().toLowerCase()}`; await db.cachedPeople.put({ id: personId, data: draft.person, updatedAt: Date.now() }); await db.cachedBicycles.put({ id: bicycleId, data: { frameNumber: draft.frameNumber, brand: draft.brand, model: draft.model, color: draft.color, distinguishingFeatures: draft.features, currentOwnerId: personId }, updatedAt: Date.now() }); await db.pendingRegistrations.put({ id: crypto.randomUUID(), payload: { bicycleId, ownerId: personId, bicycle: draft, recordedAt: new Date().toISOString() }, createdAt: Date.now() }); setIsSaving(false); onSave() }
  if (saved) return <Success title="Bicycle registered" copy="The bicycle and linked owner are saved locally and ready for sync." onDone={onCancel} />
  const steps = ['Serial', 'Bicycle', 'Person', 'Review', 'Done']
  const person = draft.person
  return <section className="flow-screen"><div className="stepper">{steps.map((label, index) => <span key={label} className={index <= (phase === 'serial' ? 0 : phase === 'bicycle' ? 1 : phase === 'person-search' || phase === 'person-new' ? 2 : 3) ? 'current' : ''}><i>{index + 1}</i><small>{label}</small></span>)}</div>
    {phase === 'serial' && <div className="flow-body"><h2>Verify bicycle serial</h2><p>Check the database before creating a registration. A bicycle serial can only be registered once.</p><label>Frame serial number<div className="serial-input"><QrCode size={16} /><input value={draft.frameNumber} onChange={(event) => { updateBicycle('frameNumber', event.target.value); setSerialChecked(false); setSerialOwner(null); setSerialConfirmed(false) }} placeholder="E.G. ABT-2024-00918" /><Smartphone size={16} /></div></label><button className="secondary-button" onClick={() => void verifySerial()}><Search size={15} /> Check bicycle database</button>{serialChecked && serialOwner && <div className="duplicate-warning"><ShieldAlert size={17} /><span><strong>Serial already registered</strong><small>This bicycle is linked to {serialOwner.name}. Resolve this issue before continuing.</small><button className="owner-details-link" onClick={() => onViewOwner(serialOwner)}>View owner details <ArrowRight size={12} /></button><div className="owner-details"><b>{serialOwner.name}</b><small>{serialOwner.nationalId} · {serialOwner.phone}</small><small>{serialOwner.sector} · {serialOwner.village}</small></div></span>{serialConfirmed ? <Check className="confirmation-check" size={17} /> : <button className="confirm-warning" onClick={() => setSerialConfirmed(true)}>Issue resolved</button>}</div>}{serialChecked && !serialOwner && <div className="verification-result not-found"><Check size={15} /><span><strong>Serial available</strong><small>No bicycle record was found. Continue to capture the bicycle.</small></span></div>}</div>}
    {phase === 'bicycle' && <div className="flow-body"><h2>Record bicycle details</h2><p>This serial is new. Capture the bicycle before linking its current owner.</p><div className="capture-summary"><span>Frame serial<strong>{draft.frameNumber}</strong></span><span className="not-found-label">Available to register</span></div><div className="two-fields"><label>Brand<input value={draft.brand} onChange={(event) => updateBicycle('brand', event.target.value)} placeholder="e.g. Trek" /></label><label>Model<input value={draft.model} onChange={(event) => updateBicycle('model', event.target.value)} placeholder="e.g. Marlin 7" /></label></div><div className="two-fields"><label>Color<input value={draft.color} onChange={(event) => updateBicycle('color', event.target.value)} placeholder="e.g. black" /></label><label>Photo reference<input placeholder="Optional photo ID" /></label></div><label>Distinguishing features<textarea value={draft.features} onChange={(event) => updateBicycle('features', event.target.value)} placeholder="Scratches, markings, accessories" /></label></div>}
    {phase === 'person-search' && <div className="flow-body"><h2>Find current owner</h2><p>Search by name or national ID. National ID is the primary person identifier.</p><label>Name or national ID<div className="search-field"><Search size={15} /><input value={personQuery} onChange={(event) => setPersonQuery(event.target.value)} placeholder="Search person in database" /></div></label><button className="secondary-button" onClick={findPerson}><Search size={15} /> Find person</button>{personChecked && person && <div className="person-found"><Check size={16} /><span><strong>{person.name}</strong><small>{person.nationalId} · {person.phone}</small><small>{person.sector} · {person.village}</small></span></div>}{personChecked && !person && <div className="person-not-found"><UserRound size={16} /><span><strong>Person not found</strong><small>No person matches this search. Add the owner to the database.</small></span><button onClick={() => setPhase('person-new')}>Add new person <ArrowRight size={14} /></button></div>}</div>}
    {phase === 'person-new' && <div className="flow-body"><h2>Add person to database</h2><p>Create the owner record first, then it will be linked to this bicycle registration.</p><label>Full name<input value={newPerson.name} onChange={(event) => updatePerson('name', event.target.value)} placeholder="Full legal name" /></label><label>National ID (primary key)<input value={newPerson.nationalId} onChange={(event) => updatePerson('nationalId', event.target.value)} placeholder="National ID number" /></label><div className="two-fields"><label>Phone<input value={newPerson.phone} onChange={(event) => updatePerson('phone', event.target.value)} placeholder="Primary phone" /></label><label>Cell<input value={newPerson.cell} onChange={(event) => updatePerson('cell', event.target.value)} placeholder="Cell number" /></label></div><div className="two-fields"><label>Sector<input value={newPerson.sector} onChange={(event) => updatePerson('sector', event.target.value)} placeholder="Sector" /></label><label>Village<input value={newPerson.village} onChange={(event) => updatePerson('village', event.target.value)} placeholder="Village" /></label></div></div>}
    {phase === 'review' && <div className="flow-body"><h2>Review registration</h2><p>Confirm the bicycle and its linked current owner before saving.</p><div className="review-summary"><span>Bicycle<strong>{draft.brand || 'New'} {draft.model || 'bicycle'} · {draft.frameNumber}</strong></span><span>Owner<strong>{person?.name}</strong></span><span>National ID<strong>{person?.nationalId}</strong></span><span>Location<strong>{person?.sector} · {person?.village}</strong></span></div><div className="audit-note"><ShieldCheck size={15} /> Registration and owner link will be audited.</div></div>}
    <div className="flow-actions"><button className="quiet-button" onClick={phase === 'serial' ? onCancel : () => setPhase(phase === 'person-new' ? 'person-search' : phase === 'review' ? 'person-search' : phase === 'person-search' ? 'bicycle' : 'serial')}>Back</button><button className="action-button" disabled={(phase === 'serial' && (!serialChecked || (Boolean(serialOwner) && !serialConfirmed))) || (phase === 'person-search' && !person) || (phase === 'person-new' && (!newPerson.name || !newPerson.nationalId)) || isSaving} onClick={() => { if (phase === 'serial') setPhase(serialOwner ? 'person-search' : 'bicycle'); else if (phase === 'bicycle') setPhase('person-search'); else if (phase === 'person-search') setPhase('review'); else if (phase === 'person-new') { setDraft((current) => ({ ...current, person: { id: `person-${newPerson.nationalId}`, ...newPerson } })); setPhase('review') } else void saveRegistration() }}>{isSaving ? 'Saving...' : phase === 'review' ? 'Save registration' : 'Continue'} <ArrowRight size={15} /></button></div>
  </section>
}
function Success({ title, copy, onDone }: { title: string; copy: string; onDone: () => void }) { return <div className="success-screen"><span><Check size={28} /></span><h2>{title}</h2><p>{copy}</p><button className="action-button" onClick={onDone}>Return to dashboard <Home size={15} /></button></div> }

function SearchScreen({ query, setQuery, onSelect }: { query: string; setQuery: (query: string) => void; onSelect: (record: BicycleRecord) => void }) { const records = mockBicycles.filter((record) => `${record.name} ${record.frameNumber} ${record.owner}`.toLowerCase().includes(query.toLowerCase())); return <section className="search-screen"><div className="search-field"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search Name, Frame, or Brand..." /></div><div className="filter-line"><span>⌕ Quick status filter</span><span>▣ Last 30 days</span></div><div className="segmented"><button>All items</button><button>Flagged</button><button>Verified</button></div><p className="result-count">Results: {records.length} found</p>{records.map((record) => <button className="search-record" key={record.id} onClick={() => onSelect(record)}><span className="record-image"><Bike size={28} /></span><span><strong>{record.name}</strong><small>{record.type} · {record.color}</small><small>⌕ {record.frameNumber}</small><em className={record.status === 'Verified' ? 'verified' : 'flagged'}>{record.status}</em></span><ChevronRight size={16} /></button>)}{records.length === 0 && <p className="empty-state">No local records found.</p>}<p className="cache-note">Offline database showing results from local cache.</p><button className="secondary-button load-button"><Cloud size={14} /> Load more records</button></section> }

function DetailsScreen({ record }: { record: BicycleRecord }) { return <section className="details-screen"><div className="detail-heading"><span><small>Reference ID</small><strong>TX-98422-BK</strong></span><em className="verified">◉ Verified</em></div><p className="detail-date"><CalendarDays size={13} /> Oct 24, 2023 | 14:32</p><div className="asset-card"><div className="asset-image"><Bike size={52} /><span>Bicycle asset</span></div><div><small>Frame serial number</small><strong>{record.frameNumber}</strong></div><div><small>Frame color</small><strong>{record.color}</strong></div></div><div className="parties-card"><h2><ArrowRight size={15} /> Transfer parties</h2><div><small>Seller (outbound)</small><strong>Marcus Thorne</strong><span>ID-55091-MT</span></div><div><small>Buyer (inbound)</small><strong>Sarah Jenkins</strong><span>ID-99281-SJ</span></div></div><div className="location-card"><MapPin size={17} /><span><small>Field location</small><strong>Field Sector 7 - Portland Central</strong><small>Duty agent</small><strong>AGENT_8821</strong></span></div><button className="action-button export-button"><Send size={14} /> Export certified record (PDF)</button></section> }

function ActivityScreen() { return <section className="activity-screen"><p className="date-divider">▣ Friday, Nov 24</p>{mockActivity.concat([['06:20 PM', 'New registration: Giant', 'Owner: Elena Rodriguez']]).map(([time, title, detail]) => <div className="activity-card" key={`${time}-${title}`}><span className="activity-mark"><ArrowRight size={16} /></span><span><strong>{title}</strong><small>{detail}</small><small># TXN-99285-A - {time}</small></span><ChevronRight size={16} /></div>)}</section> }

function ProfileScreen({ onWarning, onLogout, onAdmin }: { onWarning: () => void; onLogout: () => void; onAdmin: () => void }) { return <section className="profile-screen"><div className="profile-card"><span className="profile-avatar">MO</span><span><strong>{mockUser.name}</strong><small>Field Agent · {mockUser.location}</small></span><ChevronRight size={16} /></div><button className="settings-row"><Settings size={17} /> Field preferences <span>Unit 88 configuration</span><ChevronRight size={15} /></button><button className="settings-row"><FileText size={17} /> Agent handbook <span>v4.2.0-stable</span><ChevronRight size={15} /></button><button className="warning-row" onClick={onWarning}><ShieldAlert size={17} /> View protocol warning <ChevronRight size={15} /></button><button className="settings-row" onClick={onAdmin}><ShieldCheck size={17} /> Admin workspace preview <span>Admin</span><ChevronRight size={15} /></button><button className="logout-button" onClick={onLogout}>End session & secure logs <LockKeyhole size={15} /></button><p className="profile-footnote">Logging out will clear temporary field caches and lock the encrypted layer.</p></section> }
function BottomNav({ screen, onNavigate }: { screen: Screen; onNavigate: (screen: Screen) => void }) { return <nav className="bottom-nav">{navItems.map(({ screen: item, label, icon: Icon }) => <button className={screen === item ? 'active' : ''} key={item} onClick={() => onNavigate(item)}><Icon size={18} /><small>{label}</small></button>)}</nav> }
function AdminBottomNav({ screen, onNavigate }: { screen: Screen; onNavigate: (screen: Screen) => void }) { const items: { screen: Screen; label: string; icon: typeof Home }[] = [{ screen: 'admin-home', label: 'Home', icon: Home }, { screen: 'bicycle-inventory', label: 'Bicycles', icon: Bike }, { screen: 'registry-profile', label: 'People', icon: Users }, { screen: 'agent-management', label: 'Agents', icon: UserRound }]; return <nav className="bottom-nav admin-bottom-nav">{items.map(({ screen: item, label, icon: Icon }) => <button className={screen === item || (label === 'Bicycles' && ['admin-transactions', 'transaction-record', 'flagged-queue', 'ownership-chain'].includes(screen)) || (label === 'Agents' && ['agent-onboarding', 'agent-terminal'].includes(screen)) ? 'active' : ''} key={label} onClick={() => onNavigate(item)}><Icon size={18} /><small>{label}</small></button>)}</nav> }
function OwnerDetailsModal({ person, onClose }: { person: PersonRecord; onClose: () => void }) { return <div className="owner-modal-backdrop" role="dialog" aria-modal="true" aria-label="Owner details"><section className="owner-modal"><header><span><UserRound size={17} /> Owner details</span><button onClick={onClose} aria-label="Close owner details"><X size={18} /></button></header><div className="owner-modal-identity"><span className="profile-avatar">{person.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</span><span><strong>{person.name}</strong><small>Existing person record</small></span></div><dl><dt>National ID</dt><dd>{person.nationalId}</dd><dt>Phone</dt><dd>{person.phone}</dd><dt>Cell</dt><dd>{person.cell}</dd><dt>Sector</dt><dd>{person.sector}</dd><dt>Village</dt><dd>{person.village}</dd></dl><p className="owner-modal-note"><ShieldCheck size={14} /> This person can be linked without creating a duplicate record.</p><button className="action-button" onClick={onClose}>Return to verification</button></section></div> }
function WarningModal({ onClose }: { onClose: () => void }) { return <div className="warning-backdrop"><div className="warning-modal"><header><ShieldAlert size={28} /><button onClick={onClose}><X size={18} /></button></header><h2>Critical warning</h2><p>Ownership mismatch detected. The seller does not match the bicycle's active record. Immediate informed procedure recommended.</p><button className="action-button" onClick={onClose}>Acknowledge protocol</button><button className="quiet-button" onClick={onClose}>Dismiss</button></div></div> }
