import { useState, type ReactNode } from 'react'
import { Activity, ArrowLeft, ArrowRight, Bike, CalendarDays, Check, ChevronRight, Cloud, Database, Eye, FileText, Flag, Home, LockKeyhole, MapPin, Plus, QrCode, Search, Send, Settings, ShieldAlert, ShieldCheck, Signal, Smartphone, TrendingUp, UserRound, Users, Wifi, X } from 'lucide-react'
import { mockActivity, mockAdminTransactions, mockBicycles, mockUser, type BicycleRecord } from './mock/data'

type Screen = 'login' | 'home' | 'admin-home' | 'admin-transactions' | 'transaction-record' | 'flagged-queue' | 'bicycle-inventory' | 'ownership-chain' | 'registry-profile' | 'agent-management' | 'agent-onboarding' | 'agent-terminal' | 'reports-exports' | 'transaction' | 'register' | 'search' | 'details' | 'activity' | 'profile'
type Role = 'AGENT' | 'ADMIN'

const navItems: { screen: Screen; label: string; icon: typeof Home }[] = [
  { screen: 'home', label: 'Home', icon: Home },
  { screen: 'search', label: 'Search', icon: Search },
  { screen: 'activity', label: 'Activity', icon: Activity },
  { screen: 'profile', label: 'Profile', icon: UserRound },
]

export default function App() {
  const [screen, setScreen] = useState<Screen>('login')
  const [role, setRole] = useState<Role>('AGENT')
  const [selected, setSelected] = useState<BicycleRecord>(mockBicycles[0])
  const [query, setQuery] = useState('')
  const [transactionStep, setTransactionStep] = useState(0)
  const [saved, setSaved] = useState(false)
  const [warning, setWarning] = useState(false)

  const openDetails = (record: BicycleRecord) => { setSelected(record); setScreen('details') }
  const go = (next: Screen) => { setSaved(false); setScreen(next) }

  if (screen === 'login') return <Login onLogin={() => go('home')} />

  return <div className="terminal-shell">
    <header className="terminal-header">
      {screen !== 'home' && <button className="back-button" onClick={() => go(screen === 'details' ? 'search' : 'home')} aria-label="Go back"><ArrowLeft size={17} /></button>}
      <strong>{screenTitle(screen)}</strong>
      <span className="wifi-badge" title="Online"><Wifi size={14} /></span>
    </header>
    <div className="terminal-content">
      {screen === 'home' && <HomeScreen onNavigate={go} onSelect={openDetails} />}
      {screen === 'admin-home' && <AdminHomeScreen onNavigate={go} />}
      {screen === 'admin-transactions' && <AdminTransactionsScreen onNavigate={go} />}
      {screen === 'transaction-record' && <AdminRecordScreen onNavigate={go} />}
      {screen === 'flagged-queue' && <FlaggedQueueScreen onNavigate={go} />}
      {screen === 'bicycle-inventory' && <BicycleInventoryScreen onNavigate={go} />}
      {screen === 'ownership-chain' && <OwnershipChainScreen onNavigate={go} />}
      {screen === 'registry-profile' && <RegistryProfileScreen onNavigate={go} />}
      {screen === 'agent-management' && <AgentManagementScreen onNavigate={go} />}
      {screen === 'agent-onboarding' && <AgentOnboardingScreen onNavigate={go} />}
      {screen === 'agent-terminal' && <AgentTerminalScreen onNavigate={go} />}
      {screen === 'reports-exports' && <ReportsExportsScreen onNavigate={go} />}
      {screen === 'transaction' && <TransactionFlow step={transactionStep} setStep={setTransactionStep} saved={saved} onSave={() => setSaved(true)} onCancel={() => go('home')} />}
      {screen === 'register' && <RegisterScreen onSave={() => setSaved(true)} saved={saved} onCancel={() => go('home')} />}
      {screen === 'search' && <SearchScreen query={query} setQuery={setQuery} onSelect={openDetails} />}
      {screen === 'details' && <DetailsScreen record={selected} />}
      {screen === 'activity' && <ActivityScreen />}
      {screen === 'profile' && <ProfileScreen onWarning={() => setWarning(true)} onLogout={() => { setRole('AGENT'); go('login') }} onAdmin={() => { setRole('ADMIN'); go('admin-home') }} />}
    </div>
    {role === 'ADMIN' ? <AdminBottomNav screen={screen} onNavigate={go} /> : screen !== 'transaction' && screen !== 'register' && screen !== 'details' && <BottomNav screen={screen} onNavigate={go} />}
    {warning && <WarningModal onClose={() => setWarning(false)} />}
  </div>
}

function screenTitle(screen: Screen) {
  return { home: 'Agent Dashboard', 'admin-home': 'Biketrack Admin', 'admin-transactions': 'All Transactions', 'transaction-record': 'Transaction Record', 'flagged-queue': 'Flagged Queue', 'bicycle-inventory': 'Bicycle Inventory', 'ownership-chain': 'Ownership Chain', 'registry-profile': 'Registry Profile', 'agent-management': 'Field Agent Management', 'agent-onboarding': 'Agent Onboarding', 'agent-terminal': 'Agent Terminal', 'reports-exports': 'Reports & Exports', transaction: 'New Transaction', register: 'Register Bicycle', search: 'Search Field Records', details: 'Transaction Details', activity: 'Recent Activity', profile: 'Agent Profile & Settings', login: 'Login' }[screen]
}

function Login({ onLogin }: { onLogin: () => void }) {
  return <main className="login-screen">
    <div className="login-hero"><div className="hero-bike"><Bike size={22} /></div><strong>CycleTrack</strong><small>FIELD AGENT TERMINAL</small></div>
    <section className="login-panel"><p className="screen-kicker">SECURE ENTRY</p><p className="login-copy">Authorized personnel only. PIN required for field access.</p>
      <label><span><Smartphone size={12} /> Agent phone</span><input placeholder="000-000-0000" /></label>
      <label><span><LockKeyhole size={12} /> Security PIN</span><div className="password-input"><input type="password" placeholder="••••" /><Eye size={15} /></div></label>
      <button className="action-button" onClick={onLogin}>Initialize terminal <ArrowRight size={16} /></button>
      <button className="quiet-button">Forgot credentials?</button>
    </section>
    <footer className="offline-bar"><span><Signal size={14} /> Connectivity</span><strong>Offline-ready mode</strong><small>v2.4.1-field</small></footer>
  </main>
}

function HomeScreen({ onNavigate, onSelect }: { onNavigate: (screen: Screen) => void; onSelect: (record: BicycleRecord) => void }) {
  return <>
    <section className="welcome"><p className="screen-kicker">LOGGED IN AS FIELD AGENT</p><h1>Operations Center</h1></section>
    <button className="feature-button" onClick={() => onNavigate('transaction')}><span className="feature-icon"><FileText size={22} /></span><span><strong>New Transaction</strong><small>Initiate bicycle sale or transfer</small></span><ArrowRight /></button>
    <button className="feature-button" onClick={() => onNavigate('register')}><span className="feature-icon"><Bike size={22} /></span><span><strong>Register Bicycle</strong><small>Capture serial & owner data</small></span><ArrowRight /></button>
    <div className="quick-grid"><button onClick={() => onNavigate('search')}><Search size={20} /><strong>Search</strong></button><button onClick={() => onNavigate('activity')}><Activity size={20} /><strong>Activity</strong></button></div>
    <p className="section-label">Session intelligence</p><div className="intelligence"><div><small>Today's tasks</small><strong>12<span>/15</span></strong></div><div><small>Local cache</small><strong className="lime">42MB</strong></div><footer><Database size={13} /> Offline database v2.4.1 active</footer></div>
    <p className="section-label">Last modified record</p><button className="record-row" onClick={() => onSelect(mockBicycles[0])}><span className="record-icon"><Bike size={18} /></span><span><strong>TXN-88290-B</strong><small>◷ Modified 14 mins ago</small></span><ChevronRight size={17} /></button>
  </>
}

function AdminHomeScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) {
  const metrics = [['Total registered', '14,282', '+12.5%', TrendingUp], ['Active agents', '184', '↑ 4', Users], ['Pending sync', '42', '-8%', Cloud], ['Flagged alerts', '09', '+2', Flag]] as const
  const flags = [['Specialized Sirrus X 4.0', 'Stolen report match #SR-928', '14h ago'], ['Cannondale Topstone 1', 'Duplicate serial entry', '11h ago'], ['Trek Marlin 7 Gen 2', 'Invalid ownership transfer', '3h ago']]
  const modules = [['Transactions', 'Historical log', Activity], ['Bicycles', 'Registry inventory', Bike], ['People', 'Owner directory', Users], ['Field agents', 'Team management', UserRound], ['Reports', 'Export & analytics', FileText], ['Flagged', 'Priority queue', Flag]] as const
  return <section className="admin-home">
    <div className="admin-brand"><span>BIKETRACK ADMIN</span><small>RECORD-KEEPING CONTROL CENTER</small></div>
    <div className="admin-metrics">{metrics.map(([label, value, trend, Icon]) => <div className="admin-metric" key={label}><div><Icon size={14} /><b>{trend}</b></div><small>{label}</small><strong>{value}</strong></div>)}</div>
    <div className="admin-section-heading"><span><Flag size={13} /> Flagged queue</span><button onClick={() => onNavigate('search')}>View all</button></div><p className="admin-subtitle">Immediate resolution required</p>
    <div className="flag-list">{flags.map(([name, reason, time]) => <button key={name} className="flag-item" onClick={() => onNavigate('search')}><span><Flag size={13} /></span><strong>{name}<small>{reason}</small></strong><em>{time}</em></button>)}</div>
    <p className="admin-section-label"><TrendingUp size={11} /> Control modules</p><div className="module-grid">{modules.map(([label, copy, Icon], index) => <button key={label} className={index === 5 ? 'module danger' : 'module'} onClick={() => onNavigate(['admin-transactions', 'bicycle-inventory', 'registry-profile', 'agent-management', 'reports-exports', 'flagged-queue'][index] as Screen)}><Icon size={15} /><strong>{label}</strong><small>{copy}</small>{index === 5 && <b>!</b>}</button>)}</div>
    <button className="admin-register" onClick={() => onNavigate('register')}><Plus size={14} /> Register new bicycle</button>
    <div className="admin-footer-actions"><button onClick={() => onNavigate('profile')}>Manage profile</button><button onClick={() => onNavigate('profile')}>System settings</button></div><p className="admin-integrity">"Integrity in every record, security in every chain."<br /><span>Last sync: 5:38:30 PM (UTC-5)</span></p>
  </section>
}

function AdminTransactionsScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) {
  const [query, setQuery] = useState('')
  const transactions = mockAdminTransactions.filter((transaction) => `${transaction.id} ${transaction.bicycle} ${transaction.frameNumber} ${transaction.parties} ${transaction.agent}`.toLowerCase().includes(query.toLowerCase()))
  return <section className="admin-transactions"><div className="admin-page-heading"><div><p className="screen-kicker">CONTROL MODULE</p><h1>All Transactions</h1><p>Network-wide historical record</p></div><button className="admin-icon-button" aria-label="Export transactions"><Send size={15} /></button></div><div className="admin-transaction-stats"><span><small>Total records</small><strong>3,672</strong></span><span><small>This month</small><strong>184</strong></span><span><small>Flagged</small><strong className="rust-number">09</strong></span></div><div className="admin-search"><Search size={14} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search ID, frame, owner..." /></div><div className="admin-filters"><button className="selected">All</button><button>Sales</button><button>Transfers</button><button>Flagged</button></div><p className="admin-result-count">Showing {transactions.length} of 3,672 transactions</p><div className="transaction-list">{transactions.map((transaction) => <button className="transaction-item" key={transaction.id} onClick={() => onNavigate('transaction-record')}><div className="transaction-item-head"><span className={`transaction-type ${transaction.type.toLowerCase()}`}>{transaction.type}</span><em className={transaction.status === 'Verified' ? 'verified' : transaction.status === 'Flagged' ? 'flagged' : 'pending'}>{transaction.status}</em></div><strong>{transaction.bicycle}</strong><small className="transaction-frame">{transaction.frameNumber} · {transaction.id}</small><div className="transaction-meta"><span>{transaction.parties}</span><span>{transaction.agent}</span><span>{transaction.date}</span></div><ChevronRight size={15} /></button>)}</div>{transactions.length === 0 && <p className="empty-state">No transactions match this search.</p>}<button className="secondary-button admin-load">Load more records</button></section>
}

function AdminRecordScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) { return <AdminPanel title="Transaction Record" kicker="REFERENCE ID · TX-98422-BK"><div className="admin-record-alert"><ShieldAlert size={14} /><strong>Resolution required</strong><small>Flagged record requires administrator review.</small></div><AdminInfo title="Transaction summary" rows={['SALE · Nov 24, 2023 · 14:22 UTC', 'Specialized Sirrus X 4.0 · M2S-928', 'Marcus Thorne → Sarah Jenkins', 'Processed by AGENT_8821']} /><button className="admin-wide-button" onClick={() => onNavigate('flagged-queue')}>Open flagged queue</button></AdminPanel> }
function FlaggedQueueScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) { return <AdminPanel title="Flagged Queue" kicker="ACTIVE INCIDENTS · 3"><div className="queue-metrics"><b>12<small>Urgent</small></b><b>08<small>Pending</small></b><b>45<small>Resolved</small></b></div>{['Specialized Rockhopper Expert', 'Cannondale Synapse Carbon', 'Trek Domane AL 2'].map((name) => <button className="incident-card" key={name} onClick={() => onNavigate('transaction-record')}><Flag size={14} /><strong>{name}<small>Serial mismatch and ownership validation required</small></strong><em>Review</em></button>)}</AdminPanel> }
function BicycleInventoryScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) { return <AdminPanel title="Bicycle Inventory" kicker="REGISTRY INVENTORY"><div className="admin-search"><Search size={14} /><input placeholder="Search SN, Brand, or Owner..." /></div><div className="inventory-summary"><strong>1,284<small>Total records</small></strong><strong className="rust-number">42<small>Flagged units</small></strong></div>{mockBicycles.concat(mockBicycles).map((bike, index) => <button className="inventory-item" key={`${bike.id}-${index}`} onClick={() => onNavigate('ownership-chain')}><Bike size={18} /><strong>{bike.name}<small>SN: {bike.frameNumber} · {bike.owner}</small></strong><em>{index % 3 === 1 ? 'Flagged' : 'Registered'}</em><ChevronRight size={14} /></button>)}</AdminPanel> }
function OwnershipChainScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) { return <AdminPanel title="Ownership Chain" kicker="SPECIALIZED ROCKHOPPER ELITE"><div className="chain-card"><small>Current owner</small><strong>Marcus Vane</strong><span>Field Protocol 04</span></div>{['Registration · Feb 14, 2024', 'Transfer · Jan 20, 2024', 'Resolution · Nov 15, 2023'].map((event) => <div className="chain-event" key={event}><span></span><strong>{event}<small>Verified record with audit metadata and location.</small></strong></div>)}<button className="admin-wide-button" onClick={() => onNavigate('transaction-record')}>Full export</button></AdminPanel> }
function RegistryProfileScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) { return <AdminPanel title="Registry Profile" kicker="MARCUS V. STERLING"><div className="registry-identity"><span className="profile-avatar">MV</span><strong>Verified registry owner<small>REG-99285-MV · Sector 4 Administrative District</small></strong></div><div className="inventory-summary"><strong>2<small>Currently owned</small></strong><strong className="rust-number">1<small>System flags</small></strong></div><button className="inventory-item" onClick={() => onNavigate('bicycle-inventory')}><Bike size={18} /><strong>Specialized Rockhopper Expert<small>SP-88218-Z2 · Active residence</small></strong><em>Registered</em></button><button className="inventory-item"><Bike size={18} /><strong>Cannondale Quick Disc 3<small>CN-11923-Q · Active residence</small></strong><em>Registered</em></button></AdminPanel> }
function AgentManagementScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) { return <AdminPanel title="Field Agent Management" kicker="AUTHORIZED PERSONNEL"><div className="admin-search"><Search size={14} /><input placeholder="Search by name or ID..." /></div><div className="inventory-summary"><strong>24<small>Total</small></strong><strong>18<small>Active</small></strong><strong>06<small>Deploy</small></strong></div>{['Marcus Thorne', 'Sarah Jenkins', 'David Vance', 'Elena Rodriguez'].map((name) => <button className="agent-item" key={name} onClick={() => onNavigate('agent-terminal')}><span className="profile-avatar">{name.split(' ').map((part) => part[0]).join('')}</span><strong>{name}<small>ONLINE · Field Agent · 142 records</small></strong><ChevronRight size={14} /></button>)}<button className="admin-wide-button" onClick={() => onNavigate('agent-onboarding')}><Plus size={14} /> Onboard new agent</button></AdminPanel> }
function AgentOnboardingScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) { return <AdminPanel title="Agent Onboarding" kicker="STEP 1 OF 2"><label>Full legal name<input placeholder="e.g. Marcus Thorne" /></label><label>Assigned tactical ID<input placeholder="BT-AGENT-772" /></label><div className="two-fields"><label>Operational role<select><option>Field Agent</option><option>Supervisor</option></select></label><label>Clearance level<select><option>Level 01</option><option>Level 02</option></select></label></div><label>Official email address<input placeholder="agent.name@biketrack.gov" /></label><button className="admin-wide-button" onClick={() => onNavigate('agent-management')}>Proceed to verification <ArrowRight size={14} /></button></AdminPanel> }
function AgentTerminalScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) { return <AdminPanel title="Agent Terminal" kicker="MARCUS THORNE · LEVEL 3 AGENT"><div className="inventory-summary"><strong>12<small>Logins today</small></strong><strong>98.4%<small>Success rate</small></strong></div><p className="admin-section-label">Access protocols</p>{['New registration', 'Asset transfers', 'Flag authority', 'Remote override'].map((name, index) => <div className="protocol-row" key={name}><ShieldCheck size={14} /><strong>{name}<small>{index < 2 ? 'Allow agent to record and sync records' : 'Grant power to review suspicious assets'}</small></strong><span className={index < 2 ? 'toggle on' : 'toggle'} /></div>)}<button className="admin-wide-button" onClick={() => onNavigate('agent-management')}>Return to agents</button></AdminPanel> }
function ReportsExportsScreen({ onNavigate }: { onNavigate: (screen: Screen) => void }) { return <AdminPanel title="Reports & Exports" kicker="ADVANCED ANALYTICS"><div className="report-hero"><TrendingUp size={25} /><strong>Generate encrypted audit reports</strong><small>Industry-standard audit trails and operational summaries.</small></div>{['Transaction audit log', 'Agent performance', 'Flagged incident summary', 'Inventory status'].map((name) => <button className="report-option" key={name}><FileText size={15} /><strong>{name}<small>Full history of registry actions and transactions</small></strong><ChevronRight size={14} /></button>)}<button className="admin-wide-button" onClick={() => onNavigate('admin-home')}>Preview report data</button></AdminPanel> }
function AdminPanel({ title, kicker, children }: { title: string; kicker: string; children: ReactNode }) { return <section className="admin-panel"><p className="screen-kicker">{kicker}</p><h1>{title}</h1>{children}</section> }
function AdminInfo({ title, rows }: { title: string; rows: string[] }) { return <div className="admin-info"><h2>{title}</h2>{rows.map((row) => <p key={row}>{row}</p>)}</div> }

function TransactionFlow({ step, setStep, saved, onSave, onCancel }: { step: number; setStep: (step: number) => void; saved: boolean; onSave: () => void; onCancel: () => void }) {
  if (saved) return <Success title="Transaction queued" copy="Saved to the offline queue. It will sync when connectivity returns." onDone={onCancel} />
  const steps = ['Type', 'Serial', 'Parties', 'Review', 'Done']
  return <section className="flow-screen"><div className="stepper">{steps.map((label, index) => <span key={label} className={index <= step ? 'current' : ''}><i>{index + 1}</i><small>{label}</small></span>)}</div>
    {step === 0 && <ChoiceStep title="Select transaction type" copy="Choose the appropriate record type for this field operation." options={[['Ownership transfer (sale)', 'Permanent change of ownership', FileText], ['Rental agreement', 'Temporary transfer for a defined period', MapPin], ['Impound / recovery', 'Official law enforcement record', ShieldCheck]]} />}
    {step === 1 && <SerialStep />}
    {step === 2 && <PartyStep />}
    {step === 3 && <ReviewStep />}
    <div className="flow-actions"><button className="quiet-button" onClick={step === 0 ? onCancel : () => setStep(step - 1)}>Back</button><button className="action-button" onClick={() => step === 3 ? onSave() : setStep(step + 1)}>{step === 3 ? 'Queue transaction' : 'Continue'} <ArrowRight size={15} /></button></div>
  </section>
}

function ChoiceStep({ title, copy, options }: { title: string; copy: string; options: [string, string, typeof FileText][] }) { return <div className="flow-body"><h2>{title}</h2><p>{copy}</p>{options.map(([title, copy, Icon]) => <button className="choice-card" key={title}><span><Icon size={19} /></span><b>{title}</b><small>{copy}</small><ChevronRight /></button>)}</div> }
function SerialStep() { return <div className="flow-body"><h2>Serial number verification</h2><p>Ensure the bicycle is not already registered or reported stolen.</p><label>Frame serial number<div className="serial-input"><QrCode size={16} /><input placeholder="E.G. AB12345678" /><Smartphone size={16} /></div></label><button className="secondary-button"><Search size={15} /> Verify database</button><p className="section-label">Common serial locations</p><div className="location-grid"><span>Bottom bracket<b>Under pedals</b></span><span>Head tube<b>Front of frame</b></span><span>Seat tube<b>Near saddle</b></span><span>Rear dropout<b>Back wheel hub</b></span></div></div> }
function PartyStep() { return <div className="flow-body"><h2>Transfer parties</h2><p>Record both parties exactly as presented on their identification.</p><label>Seller (outbound)<input placeholder="Search seller by name or ID" /></label><label>Buyer (inbound)<input placeholder="Search buyer by name or ID" /></label><label>Reason for mismatch, if applicable<textarea placeholder="Required when seller differs from current owner" /></label></div> }
function ReviewStep() { return <div className="flow-body"><h2>Review before queueing</h2><p>Check the record. Flagged mismatches warn the agent but do not block recording.</p><div className="review-summary"><span>Transaction type<strong>Ownership transfer (sale)</strong></span><span>Frame serial<strong>AB12345678</strong></span><span>Parties<strong>Seller and buyer captured</strong></span><span>Location<strong>Field Sector 7 - Portland Central</strong></span></div><div className="audit-note"><ShieldCheck size={15} /> This action will be added to the audit log.</div></div> }

function RegisterScreen({ saved, onSave, onCancel }: { saved: boolean; onSave: () => void; onCancel: () => void }) { if (saved) return <Success title="Bicycle registered" copy="The registration is saved locally and ready for sync." onDone={onCancel} />; return <section className="flow-screen"><div className="flow-body"><h2>Register a bicycle</h2><p>Capture the serial, bicycle details, and current owner.</p><label>Frame serial number<input placeholder="E.G. AB12345678" /></label><div className="two-fields"><label>Brand<input placeholder="e.g. Trek" /></label><label>Model<input placeholder="e.g. Marlin 7" /></label></div><div className="two-fields"><label>Color<input placeholder="e.g. black" /></label><label>Owner<input placeholder="Search person" /></label></div><label>Distinguishing features<textarea placeholder="Scratches, markings, accessories" /></label><button className="photo-button"><Bike size={19} /> Add bicycle photo <span>+</span></button></div><div className="flow-actions"><button className="quiet-button" onClick={onCancel}>Cancel</button><button className="action-button" onClick={onSave}>Save registration <Check size={15} /></button></div></section> }
function Success({ title, copy, onDone }: { title: string; copy: string; onDone: () => void }) { return <div className="success-screen"><span><Check size={28} /></span><h2>{title}</h2><p>{copy}</p><button className="action-button" onClick={onDone}>Return to dashboard <Home size={15} /></button></div> }

function SearchScreen({ query, setQuery, onSelect }: { query: string; setQuery: (query: string) => void; onSelect: (record: BicycleRecord) => void }) { const records = mockBicycles.filter((record) => `${record.name} ${record.frameNumber} ${record.owner}`.toLowerCase().includes(query.toLowerCase())); return <section className="search-screen"><div className="search-field"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search Name, Frame, or Brand..." /></div><div className="filter-line"><span>⌕ Quick status filter</span><span>▣ Last 30 days</span></div><div className="segmented"><button>All items</button><button>Flagged</button><button>Verified</button></div><p className="result-count">Results: {records.length} found</p>{records.map((record) => <button className="search-record" key={record.id} onClick={() => onSelect(record)}><span className="record-image"><Bike size={28} /></span><span><strong>{record.name}</strong><small>{record.type} · {record.color}</small><small>⌕ {record.frameNumber}</small><em className={record.status === 'Verified' ? 'verified' : 'flagged'}>{record.status}</em></span><ChevronRight size={16} /></button>)}{records.length === 0 && <p className="empty-state">No local records found.</p>}<p className="cache-note">Offline database showing results from local cache.</p><button className="secondary-button load-button"><Cloud size={14} /> Load more records</button></section> }

function DetailsScreen({ record }: { record: BicycleRecord }) { return <section className="details-screen"><div className="detail-heading"><span><small>Reference ID</small><strong>TX-98422-BK</strong></span><em className="verified">◉ Verified</em></div><p className="detail-date"><CalendarDays size={13} /> Oct 24, 2023 | 14:32</p><div className="asset-card"><div className="asset-image"><Bike size={52} /><span>Bicycle asset</span></div><div><small>Frame serial number</small><strong>{record.frameNumber}</strong></div><div><small>Frame color</small><strong>{record.color}</strong></div></div><div className="parties-card"><h2><ArrowRight size={15} /> Transfer parties</h2><div><small>Seller (outbound)</small><strong>Marcus Thorne</strong><span>ID-55091-MT</span></div><div><small>Buyer (inbound)</small><strong>Sarah Jenkins</strong><span>ID-99281-SJ</span></div></div><div className="location-card"><MapPin size={17} /><span><small>Field location</small><strong>Field Sector 7 - Portland Central</strong><small>Duty agent</small><strong>AGENT_8821</strong></span></div><button className="action-button export-button"><Send size={14} /> Export certified record (PDF)</button></section> }

function ActivityScreen() { return <section className="activity-screen"><p className="date-divider">▣ Friday, Nov 24</p>{mockActivity.concat([['06:20 PM', 'New registration: Giant', 'Owner: Elena Rodriguez']]).map(([time, title, detail]) => <div className="activity-card" key={`${time}-${title}`}><span className="activity-mark"><ArrowRight size={16} /></span><span><strong>{title}</strong><small>{detail}</small><small># TXN-99285-A - {time}</small></span><ChevronRight size={16} /></div>)}</section> }

function ProfileScreen({ onWarning, onLogout, onAdmin }: { onWarning: () => void; onLogout: () => void; onAdmin: () => void }) { return <section className="profile-screen"><div className="profile-card"><span className="profile-avatar">MO</span><span><strong>{mockUser.name}</strong><small>Field Agent · {mockUser.location}</small></span><ChevronRight size={16} /></div><button className="settings-row"><Settings size={17} /> Field preferences <span>Unit 88 configuration</span><ChevronRight size={15} /></button><button className="settings-row"><FileText size={17} /> Agent handbook <span>v4.2.0-stable</span><ChevronRight size={15} /></button><button className="warning-row" onClick={onWarning}><ShieldAlert size={17} /> View protocol warning <ChevronRight size={15} /></button><button className="settings-row" onClick={onAdmin}><ShieldCheck size={17} /> Admin workspace preview <span>Admin</span><ChevronRight size={15} /></button><button className="logout-button" onClick={onLogout}>End session & secure logs <LockKeyhole size={15} /></button><p className="profile-footnote">Logging out will clear temporary field caches and lock the encrypted layer.</p></section> }
function BottomNav({ screen, onNavigate }: { screen: Screen; onNavigate: (screen: Screen) => void }) { return <nav className="bottom-nav">{navItems.map(({ screen: item, label, icon: Icon }) => <button className={screen === item ? 'active' : ''} key={item} onClick={() => onNavigate(item)}><Icon size={18} /><small>{label}</small></button>)}</nav> }
function AdminBottomNav({ screen, onNavigate }: { screen: Screen; onNavigate: (screen: Screen) => void }) { const items: { screen: Screen; label: string; icon: typeof Home }[] = [{ screen: 'admin-home', label: 'Home', icon: Home }, { screen: 'bicycle-inventory', label: 'Bicycles', icon: Bike }, { screen: 'registry-profile', label: 'People', icon: Users }, { screen: 'agent-management', label: 'Agents', icon: UserRound }]; return <nav className="bottom-nav admin-bottom-nav">{items.map(({ screen: item, label, icon: Icon }) => <button className={screen === item || (label === 'Bicycles' && ['admin-transactions', 'transaction-record', 'flagged-queue', 'ownership-chain'].includes(screen)) || (label === 'Agents' && ['agent-onboarding', 'agent-terminal'].includes(screen)) ? 'active' : ''} key={label} onClick={() => onNavigate(item)}><Icon size={18} /><small>{label}</small></button>)}</nav> }
function WarningModal({ onClose }: { onClose: () => void }) { return <div className="warning-backdrop"><div className="warning-modal"><header><ShieldAlert size={28} /><button onClick={onClose}><X size={18} /></button></header><h2>Critical warning</h2><p>Ownership mismatch detected. The seller does not match the bicycle's active record. Immediate informed procedure recommended.</p><button className="action-button" onClick={onClose}>Acknowledge protocol</button><button className="quiet-button" onClick={onClose}>Dismiss</button></div></div> }
