import type { Response } from 'express'
import { z } from 'zod'
import { audit } from '../audit.js'
import { asyncRoute } from '../errors.js'
import { prisma, type PrismaTx } from '../prisma.js'
import type { AuthRequest } from '../middleware/auth.js'

const input = z.object({ bicycleId: z.string().cuid(), ownerId: z.string().cuid(), clientOperationId: z.string().min(8).max(120) })
export async function listRegistrations(request: AuthRequest, response: Response) { const query = z.object({ bicycleId: z.string().cuid().optional(), ownerId: z.string().cuid().optional(), page: z.coerce.number().int().min(1).default(1), limit: z.coerce.number().int().min(1).max(100).default(20) }).parse(request.query); const where = { ...(query.bicycleId ? { bicycleId: query.bicycleId } : {}), ...(query.ownerId ? { ownerId: query.ownerId } : {}) }; const data = await prisma.registration.findMany({ where, skip: (query.page - 1) * query.limit, take: query.limit, orderBy: { createdAt: 'desc' }, include: { bicycle: { select: { id: true, frameNumber: true, brand: true, model: true } }, owner: { select: { id: true, name: true, nationalId: true, phone: true, cell: true, sector: true, village: true, nationalIdPhotoUrl: true } }, recordingAgent: { select: { id: true, name: true } } } }); return response.json({ data }) }
export async function createRegistration(request: AuthRequest, response: Response) { const body = input.parse(request.body); const existing = await prisma.syncOperation.findUnique({ where: { clientOperationId: body.clientOperationId } }); if (existing?.status === 'APPLIED' && existing.entityId) return response.json({ data: await prisma.registration.findUnique({ where: { id: existing.entityId } }), idempotent: true }); const registration = await prisma.$transaction(async (tx: PrismaTx) => { const created = await tx.registration.create({ data: { bicycleId: body.bicycleId, ownerId: body.ownerId, recordingAgentId: request.user!.id } }); await tx.bicycle.update({ where: { id: body.bicycleId }, data: { currentOwnerId: body.ownerId } }); await tx.syncOperation.upsert({ where: { clientOperationId: body.clientOperationId }, create: { clientOperationId: body.clientOperationId, userId: request.user!.id, entity: 'Registration', entityId: created.id, payload: request.body, status: 'APPLIED' }, update: { entityId: created.id, status: 'APPLIED' } }); await tx.auditLog.create({ data: { userId: request.user!.id, action: 'BICYCLE_REGISTERED', entity: 'Registration', entityId: created.id, metadata: { bicycleId: body.bicycleId, ownerId: body.ownerId } } }); return created }); await audit(request.user!.id, 'REGISTRATION_CONFIRMED', 'Registration', registration.id); return response.status(201).json({ data: registration }) }
export const registrationHandlers = { listRegistrations: asyncRoute(listRegistrations), createRegistration: asyncRoute(createRegistration) }
